### ISSUE TITLE
Convert to MonoGame?

### ISSUE THREAD

**Issue by rbwhitaker** [rbwhitaker/realm-factory#1]
This is likely a rather big undertaking, but Realm Factory would be instantly more valuable if it could work for MonoGame. Having it still work for XNA might be an OK thing to do, but there's also probably not a lot of value in trying to maintain that at this point. So if whatever anybody wants to do to make this happen removes the ability to work with XNA, that would be acceptable.

**Comment by jgedri** [comment]
Hope you don't mind if I give it a try.

**Comment by rbwhitaker** [comment]
#30 should fix this.
