### ISSUE TITLE
[BUG] The Common and Common.WinForms projects are missing from the repo

### ISSUE THREAD

**Issue by rbwhitaker** [rbwhitaker/realm-factory#23]
**Describe the bug**
You can't make a build because the solution references two projects that are not contained in the repository.

**To Reproduce**
1. Clone the source code.
2. Try to compile.

**Expected behavior**
A fresh clone on a fresh computer should be able to build the software, as long as they have VS 2013 and XNA installed, as the README document describes.

**Additional context**
None.

**Comment by jgedri** [comment]
Visual Studio says it can't find a project called Starbound.

**Comment by rbwhitaker** [comment]
> Visual Studio says it can't find a project called Starbound.

@jgedri did you start from the `master` branch? I think I got a fix for your problem, but it hasn't been merged to `master` yet. I need to do that.

**Comment by rbwhitaker** [comment]
I just merged a pull request in that fixes this issue. `develop` and `master` both should now have this fix.
